# Generated by Django 3.2 on 2023-05-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0037_auto_20230503_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofhousemodel',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='listofworkmodel',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
