# Generated by Django 3.2 on 2023-05-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0038_auto_20230503_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='RefreshCheck',
        ),
        migrations.AddField(
            model_name='listofhousemodel',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='listofworkmodel',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
