# Generated by Django 3.2 on 2023-05-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0039_auto_20230509_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeOfList',
        ),
    ]
