# Generated by Django 3.2 on 2023-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0040_delete_typeoflist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofhousemodel',
            name='header',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='listofhousemodel',
            name='type',
            field=models.CharField(default='other', max_length=255),
        ),
        migrations.AlterField(
            model_name='listofworkmodel',
            name='header',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='listofworkmodel',
            name='type',
            field=models.CharField(default='other', max_length=255),
        ),
    ]
