# Generated by Django 3.2 on 2023-07-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0042_unwantedlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('type', models.TextField(default='unwanted')),
            ],
        ),
        migrations.DeleteModel(
            name='UnwantedList',
        ),
    ]
